# image: zkm-prover:latest => https://github.com/zkMIPS/zkm-prover/blob/main/Dockerfile
# image: gnark-plonky2-verifier:latest => https://github.com/zkMIPS/gnark-plonky2-verifier/blob/main/Dockerfile
version: "3.5"
networks:
  default:
    name: zkm-prover
services:
  zkm-stage:
    container_name: zkm-stage
    restart: unless-stopped
    depends_on:
      zkm-prover1:
        condition: service_started
      zkm-prover2:
        condition: service_started
      zkm-snark:
        condition: service_started
    image: zkm-prover:latest
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M
    ports:
      - 50000:50000
    environment:
      - RUST_LOG=info
    volumes:
      - ./service/config/config_docker_compose.toml:/usr/local/bin/config.toml
      - /tmp/zkm-prover/data:/zkm/data
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/service --config /usr/local/bin/config.toml"

  zkm-prover1:
    container_name: zkm-prover1
    restart: unless-stopped
    image: zkm-prover:latest
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 256M
    environment:
      - RUST_LOG=info
    volumes:
      - ./service/config/config_docker_compose.toml:/usr/local/bin/config.toml
      - /tmp/zkm-prover/data:/zkm/data
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/service --config /usr/local/bin/config.toml"
    
  zkm-prover2:
    container_name: zkm-prover2
    restart: unless-stopped
    image: zkm-prover:latest
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 256M
    environment:
      - RUST_LOG=info
    volumes:
      - ./service/config/config_docker_compose.toml:/usr/local/bin/config.toml
      - /tmp/zkm-prover/data:/zkm/data
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/local/bin/service --config /usr/local/bin/config.toml"

  zkm-snark:
    container_name: zkm-snark
    restart: unless-stopped
    image: gnark-plonky2-verifier:latest
    volumes:
      - /tmp/zkm-prover/data:/zkm/data
    command: >
      /usr/local/bin/start.sh
