[package]
name = "prover_v2"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
serde_json = "1.0.140"
tokio = "1.44.0"
chrono = "0.4.40"
serde = { version = "1.0.219", features = ["derive", "rc"] }
deadpool-redis = { version = "0.20.0", features = ["tokio-comp"] }
redis = { version = "0.29.1", features = ["aio", "tokio-comp", "connection-manager"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17" }
tracing-forest = { version = "0.1.6", default-features = false }
bincode = "1.3.3"
anyhow = "1.0.97"

zkm2-core-machine = { path = "../../zkm2/crates/core/machine" }
zkm2-core-executor = { path = "../../zkm2/crates/core/executor" }
zkm2-stark = { path = "../../zkm2/crates/stark" }
zkm2-prover = { path = "../../zkm2/crates/prover" }
zkm2-recursion-compiler = { path = "../../zkm2/crates/recursion/compiler" }
zkm2-recursion-core = { path = "../../zkm2/crates/recursion/core" }
zkm2-sdk = { path = "../../zkm2/crates/sdk" }

p3-field = { git = "https://github.com/zkMIPS/Plonky3" }
p3-maybe-rayon = { git = "https://github.com/zkMIPS/Plonky3" }

common = { path = "../common" }

[features]
debug = []