addr = "0.0.0.0:50000"
prover_addrs = ["localhost:50001"]
metrics_addr = "0.0.0.0:50012"
database_url = "mysql://stage:123456@localhost:3306/zkm2"
base_dir = "/tmp/zkm/test/test_proof"
fileserver_url = "http://0.0.0.0:40000/test/test_proof"
proving_key_paths = ["/tmp/input-null/", "/tmp/input"]

ca_cert_path = "/home/ubuntu/sd/zkm-prover/tools/certs/ca.pem"
cert_path = "/home/ubuntu/sd/zkm-prover/tools/certs/stage.pem"
key_path = "/home/ubuntu/sd/zkm-prover/tools/certs/stage.key"