name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgresql://root:password@localhost:5432/state
  RUST_BACKTRACE: 1
  RUST_LOG: info
  SQLX_OFFLINE: 1

jobs:
  build_and_test:
    name: Rust build/test - ${{ matrix.feature }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ prover, prover_v2 ]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: root
          POSTGRES_DB: state
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Auth for GitHub Private Repo
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:@github.com/".insteadOf "https://github.com/"
          mkdir -p .cargo
          echo "[net]" >> .cargo/config.toml
          echo "git-fetch-with-cli = true" >> .cargo/config.toml

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy

      - run: curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/zkMIPS/toolchain/refs/heads/main/setup.sh | sh
      - name: Install Dependencies
        run: sudo apt install protobuf-compiler
      - name: Cargo Build
        run: source ~/.zkm-toolchain/env && cargo build --release --verbose --features=${{ matrix.feature }}
      - name: Cargo Test
        run: source ~/.zkm-toolchain/env && cargo test --release --verbose --features=${{ matrix.feature }}
      - name: Clippy
        run: source ~/.zkm-toolchain/env && cargo clippy --all-targets --features=${{ matrix.feature }} -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check