name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgresql://root:password@localhost:5432/state
  RUST_BACKTRACE: 1
  RUST_LOG: info
  SQLX_OFFLINE: 1

jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: root
          POSTGRES_DB: state
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install Dependencies
        run: sudo apt install protobuf-compiler
      - name: Cargo Test with prover
        run: cargo test --release --features=prover
      - name: Cargo Test with prover_v2
        run: cargo test --release --features=prover_v2

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - name: Install Dependencies
        run: sudo apt install protobuf-compiler
      - run: cargo clippy --features=prover --all-targets -- -D warnings
      - run: cargo clippy --features=prover_v2 --all-targets -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check